### ISSUE TITLE
Bug that occurs when using replaceable parts

### ISSUE THREAD

**Issue by itfourp** [oribella/aurelia-sortable#44] opened 2017-12-14 12:30 UTC
When I use replaceable parts in combination with multiple sortables the 'wrong' replace-part template is shown in the sortable under certain circumstances. Since it's pretty hard to explain I'd like to show the issue with a simplistic example, that can be found here:

https://github.com/itfourp/aurelia-oribella-sortable-replaceable-bugreport

I guess it has something to do with caching, but I have no idea where to look. I appreciate any help you can provide.

Best regards.

**Comment by stoffeastrom** [comment] 2017-12-15 10:18
HI @itfourp what version of `jspm` are you using? I get an error following the instructions

**Comment by itfourp** [comment] 2017-12-15 13:21
@stoffeastrom Nice, thank you! I'll have a look at this.

**Comment by stoffeastrom** [comment] 2017-12-16 10:33
@itfourp Of course, as long as we document it! So if you need touch support you have to handle it differently.

Just make a PR and we'll get it in :)

**Comment by itfourp** [comment] 2018-01-03 08:16
@stoffeastrom Okay, to use touch support I need to re-attach the touchstart-event-listener to the moved element after it was moved, or is there another way to solve this?

**Comment by stoffeastrom** [comment] 2018-01-03 10:57
@itfourp 

I guess this could be reproduced without this plugin? Since it's about the `view-cache` it could be how it's handled in Aurelia. I actually thinks this is a bug in Aurelia and how it handles the `view-cache`. If so it should be fixed there. Can you create an issue there?

Lets start there and see how it plays out. Else we could look into your approach above!

**Comment by itfourp** [comment] 2018-01-03 11:01
You're right, that's probably the best way to start!

**Comment by Alexander-Taran** [comment] 2018-03-22 09:19
Ok guys. Could you clarify the issue in aurelia repo? 
https://github.com/aurelia/templating/issues/595

Have you explored any ways to fix it?
As it is now it is pretty non-actionable.
But it might hurt somebody else.

**Comment by itfourp** [comment] 2018-03-22 09:49
I had a look at the aurelia-templating library right after I discovered the problem but I was unable to find an appropriate way to fix this issue. That's mostly because I could not identify/discern what DocumentFragment is used as template for the ViewFactory.
https://github.com/aurelia/templating/blob/b9d927c4787c4aa4ea2dcfdbf1a2f1e5cc7d6c2b/src/view-factory.js#L352
https://github.com/aurelia/templating/blob/b9d927c4787c4aa4ea2dcfdbf1a2f1e5cc7d6c2b/src/view-factory.js#L391
I'm pretty much stuck with this point, but maybe I was just looking at the wrong part of the code?

**Comment by stoffeastrom** [comment] 2018-04-24 20:38
This issue was moved to oribella/oribella#25

**Closed by stoffeastrom** 2018-04-24 20:38 UTC
