### ISSUE TITLE
IE 10 Swipe.update data.pointer[0] is undefined

### ISSUE THREAD

**Issue by doubleaa93** [oribella/aurelia-sortable#40] opened 2017-06-09 20:27 UTC
I'm not sure if IE 10 is supported but when dragging an item there is an error in the Swipe update function where it tries to access data.pointers[0] but the array empty. 

This only happens on IE 10.

**Comment by stoffeastrom** [comment] 2017-06-10 09:11
HI @doubleaa93 thanks for the info. The idea was that it could be supported. Not sure what the problem is.  Needs some investigation

**Comment by stoffeastrom** [comment] 2017-06-11 17:06
@doubleaa93 I think I understand what the problem is. Checked through the framework and for the `MSPointerFlow` the pointers are not set :/. It inherits from `PointerFlow` and the cases for `MSPointerStart` and `MSPointerMove` is missing..

**Comment by stoffeastrom** [comment] 2017-06-11 17:20
@doubleaa93 should be fixed in https://github.com/oribella/framework/commit/36b0da5afcb44f540bc291e199ffbf6b79a264a4
and `oribella-framework@0.10.3` just run an update and it should be fine.

**Comment by doubleaa93** [comment] 2017-06-13 13:12
Awesome it's working now!

**Closed** 2017-06-13 13:12 UTC
